[package]
name = "wallet-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
sov-universal-wallet = { git = "https://@github.com/Sovereign-Labs/sovereign-sdk.git", rev = "1578adfb0395abc77d9bac660a4f9f3a513b717d", package = "sov-universal-wallet", features = [
  "serde",
  "eip712"
] }
