[package]
name = "wallet-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
sov-universal-wallet = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "8eae7bd90a9821b117ea100b125ea1a5c93e9759", package = "sov-universal-wallet", features = [
  "serde",
] }
