[package]
name = "wallet-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
sov-universal-wallet = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "0214aea8cefb685f95c9d4f39d350ebafb07304f", package = "sov-universal-wallet", features = [
  "serde",
] }
