[package]
name = "wallet-wasm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
sov-universal-wallet = { git = "https://@github.com/Sovereign-Labs/sovereign-sdk.git", rev = "6f845e5c8949d86eb4c3f1a0acb35cd02df6bf55", package = "sov-universal-wallet", features = [
  "serde",
  "eip712"
] }
