[package]
name = "fuzz_input"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.93"
serde-wasm-bindgen = "0.6.5"

sov-universal-wallet = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "b7fbb4ef15628cf4aaa79f99cad9d56de6994613", package = "sov-universal-wallet", features = [
  "serde",
] }
sov-modules-api = { git = "ssh://git@github.com/Sovereign-Labs/sovereign-sdk-wip.git", rev = "b7fbb4ef15628cf4aaa79f99cad9d56de6994613" }
